### PR TITLE
 [BUG] Peaks upstream first or downstream last gene not annotated

### PR DESCRIPTION
**Pull request by klugem**
Peaks upstream first or downstream last gene not annotated.
Proposed fix is attached.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
can you give a demo example as in <https://github.com/GuangchuangYu/ChIPseeker/pull/6> to explain these commits.

Thank you!

**Comment by klugem** [comment]
The example source code generates 100000 peaks upstream of the start index of the first annotated gene and 100000 peaks downstream of the last annotated gene. Also one gene on chr1 [1000000, 1000249] is created. 

Annotation of these peaks leads to that output:
> annotatePeak(all, tssRegion=c(-3000,500), TxDb=txdb)
>> preparing features information...		 2016-01-19 04:50:49 PM 
>> identifying nearest features...		 2016-01-19 04:50:49 PM 
>> calculating distance from peak to TSS...	 2016-01-19 04:50:50 PM 
>> assigning genomic annotation...		 2016-01-19 04:50:50 PM 
>> assigning chromosome lengths			 2016-01-19 04:50:53 PM 
>> done...					 2016-01-19 04:50:53 PM 
Annotated peaks generated by ChIPseeker
1/200001  peaks were annotated

So only the peak on chr1 was annotated and no nearest gene was found for all other peaks.
[bug_first_last_sim.R.zip](https://github.com/GuangchuangYu/ChIPseeker/files/96156/bug_first_last_sim.R.zip)

**Comment by GuangchuangYu** [comment]
This is great. Thank you for your contribution!

I add you as a contributor in author list, see <https://github.com/GuangchuangYu/ChIPseeker/blob/master/DESCRIPTION>. Please update your personal information.

**Comment by klugem** [comment]
I added my email address :)

**Comment by GuangchuangYu** [comment]
🍻

**Pull request merged**
